Removes $ sign when importing gist with multiple files
When you import a gist with multiple files via url, $ is added at the beginning of each file, which causes compilation error:

https://github.com/integer32llc/rust-playground/issues/289

So this change fixes the problem.